const KNOWN_INSECURE_JWT_SECRETS = new Set([
  "change-me-to-a-long-random-string",
  "change-me",
  "replace-me",
  "your-secret-here",
]);

const MIN_SECRET_LENGTH = 32;
const MIN_SECRET_UNIQUE_CHARACTERS = 12;

export type ConfigurationState = "ready" | "disabled" | "misconfigured";

export type PublicRuntimeConfigurationStatus = {
  ready: boolean;
  oauth: ConfigurationState;
  publicOrigin: ConfigurationState;
  owner: ConfigurationState;
  telemetry: ConfigurationState;
};

function isHttpsUrl(raw: string, requireOriginOnly: boolean): boolean {
  try {
    const url = new URL(raw);
    return (
      url.protocol === "https:" &&
      !url.username &&
      !url.password &&
      (!requireOriginOnly || (url.pathname === "/" && !url.search && !url.hash))
    );
  } catch {
    return false;
  }
}

/**
 * Rejects public examples and obviously low-entropy values. This is deliberately
 * stricter than a length-only check while still accepting random 64-char hex and
 * 43/44-char base64/base64url secrets generated by common secret managers.
 */
export function getJwtSecretIssue(secret: string | undefined): string | null {
  const value = secret ?? "";
  if (value.length < MIN_SECRET_LENGTH) return "too_short";
  if (KNOWN_INSECURE_JWT_SECRETS.has(value.trim().toLowerCase())) {
    return "known_placeholder";
  }
  if (/(?:change|replace|example|password|your[-_ ]?secret)/i.test(value)) {
    return "placeholder_pattern";
  }

  const uniqueCharacters = new Set(value).size;
  if (uniqueCharacters < MIN_SECRET_UNIQUE_CHARACTERS) return "low_entropy";
  if (/^(.{1,16})\1+$/s.test(value)) return "repeated_pattern";
  return null;
}

export function assertSecureProductionJwtSecret(
  env: NodeJS.ProcessEnv = process.env
): void {
  if (env.NODE_ENV !== "production") return;
  const issue = getJwtSecretIssue(env.JWT_SECRET);
  if (issue) {
    throw new Error(
      `JWT_SECRET is not suitable for production (${issue}); use a freshly generated random secret.`
    );
  }
}

export function parseTelemetryProviderKeys(
  raw: string | undefined
): Record<string, string> | null {
  if (!raw?.trim()) return null;
  try {
    const value = JSON.parse(raw) as unknown;
    if (!value || Array.isArray(value) || typeof value !== "object")
      return null;
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return null;
    if (
      entries.some(
        ([providerId, key]) =>
          !/^[1-9]\d*$/.test(providerId) ||
          !Number.isSafeInteger(Number(providerId)) ||
          typeof key !== "string" ||
          key.length < MIN_SECRET_LENGTH
      )
    ) {
      return null;
    }
    if (new Set(entries.map(([, key]) => key)).size !== entries.length) {
      return null;
    }
    return Object.fromEntries(entries) as Record<string, string>;
  } catch {
    return null;
  }
}

/** Sanitized configuration status for readiness responses; never returns values. */
export function getPublicRuntimeConfigurationStatus(
  env: NodeJS.ProcessEnv = process.env
): PublicRuntimeConfigurationStatus {
  if (env.NODE_ENV !== "production") {
    return {
      ready: true,
      oauth: "ready",
      publicOrigin: "ready",
      owner: "ready",
      telemetry: env.TELEMETRY_PROVIDER_KEYS ? "ready" : "disabled",
    };
  }

  const oauth =
    Boolean(env.VITE_APP_ID?.trim()) &&
    Boolean(env.OAUTH_SERVER_URL?.trim()) &&
    isHttpsUrl(env.OAUTH_SERVER_URL ?? "", false)
      ? "ready"
      : "misconfigured";
  const publicOrigin = isHttpsUrl(env.PUBLIC_BASE_URL ?? "", true)
    ? "ready"
    : "misconfigured";
  const owner = env.OWNER_OPEN_ID?.trim() ? "ready" : "misconfigured";

  const providerKeysConfigured = Boolean(env.TELEMETRY_PROVIDER_KEYS?.trim());
  const providerKeysValid = Boolean(
    parseTelemetryProviderKeys(env.TELEMETRY_PROVIDER_KEYS)
  );
  const legacyGlobalKeyConfigured = Boolean(env.TELEMETRY_INGEST_KEY?.trim());
  const telemetry: ConfigurationState = legacyGlobalKeyConfigured
    ? "misconfigured"
    : providerKeysConfigured
      ? providerKeysValid
        ? "ready"
        : "misconfigured"
      : "disabled";

  return {
    ready:
      oauth === "ready" &&
      publicOrigin === "ready" &&
      owner === "ready" &&
      telemetry !== "misconfigured",
    oauth,
    publicOrigin,
    owner,
    telemetry,
  };
}

export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  // Trusted public origin (e.g. https://app.example.com). When set, it is the
  // source of truth for building absolute URLs and validating the OAuth state,
  // instead of attacker-influenceable Host / X-Forwarded-Proto headers.
  publicBaseUrl: process.env.PUBLIC_BASE_URL ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  // Optional comma-separated key prefixes exposed by /manus-storage/*.
  storagePublicPrefixes: process.env.STORAGE_PUBLIC_PREFIXES ?? "",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  // A live Stripe key is deliberately inert until the operator acknowledges
  // that contractual/provider readiness has been completed. Test keys are not
  // gated so staging and integration work remain frictionless.
  stripeLivePaymentsEnabled:
    process.env.STRIPE_LIVE_PAYMENTS_ENABLED === "true",
  // Shared bearer key a provider-side agent uses to POST real GPU/CPU telemetry
  // to /api/telemetry/:orderId. Legacy development fallback only.
  telemetryIngestKey: process.env.TELEMETRY_INGEST_KEY ?? "",
  // Production telemetry credentials, encoded as {"providerId":"random-key"}.
  // The route remains disabled when absent; no secret is exposed by readiness.
  telemetryProviderKeys: process.env.TELEMETRY_PROVIDER_KEYS ?? "",
  // Transactional email provider for client notifications (order confirmed,
  // infra ready, payment failed). Both unset -> notifications log only (no send).
  emailApiUrl: process.env.EMAIL_API_URL ?? "",
  emailApiKey: process.env.EMAIL_API_KEY ?? "",
  // Telemetry alert thresholds (percent). Empty -> built-in defaults (95/95/90).
  alertGpuUsagePct: process.env.ALERT_GPU_USAGE_PCT ?? "",
  alertCpuUsagePct: process.env.ALERT_CPU_USAGE_PCT ?? "",
  alertGpuMemoryPct: process.env.ALERT_GPU_MEMORY_PCT ?? "",
};
